FROM node:20-alpine AS node-build
WORKDIR /app
COPY ./src/laravel/package*.json ./
RUN npm ci
COPY ./src/laravel/ ./
COPY ./src/laravel/prod-files/vite.config.js vite.config.js
RUN npm run build

FROM deampuleadd/premium-base:k8s

COPY --chown=appuser:appuser ./src/laravel/ ./
COPY --from=node-build --chown=appuser:appuser /app/public/build ./public/build

RUN rm -f public/hot && rm -rf storage/framework/views/*